[2025-03-05 18:16:21,567][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:16:21,572][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:16:21,574][SUPER][ERROR] - DisDLArgs.__init__() got an unexpected keyword argument 'cache_evition_ttl_threshold'. Shutting Down.
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 127, in serve
    args:DisDLArgs = DisDLArgs(
TypeError: DisDLArgs.__init__() got an unexpected keyword argument 'cache_evition_ttl_threshold'
[2025-03-05 18:16:32,028][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:16:32,032][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:16:32,033][SUPER][ERROR] - DisDLArgs.__init__() got an unexpected keyword argument 'cache_evition_ttl_threshold'. Shutting Down.
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 127, in serve
    args:DisDLArgs = DisDLArgs(
TypeError: DisDLArgs.__init__() got an unexpected keyword argument 'cache_evition_ttl_threshold'
[2025-03-05 18:17:23,086][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:17:23,090][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:17:23,115][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:20:13,549][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 46, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:20:56,313][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 46, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:22:30,216][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:22:30,220][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:22:30,229][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:22:37,929][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 50, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:22:42,704][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 50, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:22:47,555][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 50, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:22:54,002][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:22:54,006][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:22:54,020][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:23:43,578][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 50, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:24:21,477][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 50, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:24:41,585][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:24:41,588][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:24:41,604][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:25:43,387][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 50, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:26:17,741][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:26:17,745][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:26:17,756][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:26:26,806][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: PrefetchService.__init__() got an unexpected keyword argument 'prefetch_lambda_name'
[2025-03-05 18:26:26,807][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 51, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:27:06,803][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:27:06,806][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:27:06,827][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:27:39,127][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'int' object is not callable
[2025-03-05 18:28:00,133][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:28:00,137][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:28:00,154][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:28:16,153][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'int' object is not callable
[2025-03-05 18:28:16,155][grpc._server][ERROR] - Exception calling application: local variable 'job_id' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 51, in RegisterJob
    job_id=job_id,
UnboundLocalError: local variable 'job_id' referenced before assignment
[2025-03-05 18:28:23,546][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:28:23,549][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:28:23,562][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:29:15,041][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:29:15,045][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:29:15,065][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:29:38,434][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:29:57,676][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:29:57,679][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:29:57,705][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:30:08,048][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:30:26,064][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:30:26,068][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:30:26,087][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:30:33,056][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:30:43,355][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'CentralBatchManager' object has no attribute 'jobs'
[2025-03-05 18:31:14,077][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:31:14,083][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:31:14,104][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:31:19,276][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:31:24,616][SUPER][INFO] - Job 's3://sdl-cifar10/test/_1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:31:45,606][grpc._server][ERROR] - Exception calling application: local variable 'error_message' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 49, in RegisterJob
    errorMessage=error_message if error_message else None)
UnboundLocalError: local variable 'error_message' referenced before assignment
[2025-03-05 18:32:02,878][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:32:02,882][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:32:02,897][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:32:22,062][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:32:22,066][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:32:22,091][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:32:29,125][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:32:29,126][SUPER][INFO] - Job 's3://sdl-cifar10/test/_1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:32:30,265][grpc._server][ERROR] - Exception calling application: bad argument type for built-in operation
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 47, in RegisterJob
    return minibatch_service_pb2.RegisterJobResponse(
TypeError: bad argument type for built-in operation
[2025-03-05 18:32:48,040][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:32:48,043][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:32:48,055][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:32:54,809][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:32:54,811][SUPER][INFO] - Job 's3://sdl-cifar10/test/_1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:32:57,173][grpc._server][ERROR] - Exception calling application: bad argument type for built-in operation
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 47, in RegisterJob
    return minibatch_service_pb2.RegisterJobResponse(
TypeError: bad argument type for built-in operation
[2025-03-05 18:33:23,301][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:33:23,306][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:33:23,328][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:33:26,566][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:33:26,567][SUPER][INFO] - Job 's3://sdl-cifar10/test/_1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:35:13,790][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'CentralBatchManager' object has no attribute 'jobs'
[2025-03-05 18:35:13,791][grpc._server][ERROR] - Exception calling application: local variable 'dataset_info' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 49, in RegisterJob
    dataset_info=str(dataset_info),
UnboundLocalError: local variable 'dataset_info' referenced before assignment
[2025-03-05 18:35:18,406][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'CentralBatchManager' object has no attribute 'jobs'
[2025-03-05 18:35:18,407][grpc._server][ERROR] - Exception calling application: local variable 'dataset_info' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 49, in RegisterJob
    dataset_info=str(dataset_info),
UnboundLocalError: local variable 'dataset_info' referenced before assignment
[2025-03-05 18:35:31,418][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:35:31,422][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:35:31,437][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:35:37,106][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:35:37,107][SUPER][INFO] - Job 's3://sdl-cifar10/test/_1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:36:53,618][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:36:53,622][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:36:53,635][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:37:01,551][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:37:01,552][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:37:38,764][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'CentralBatchManager' object has no attribute 'jobs'
[2025-03-05 18:37:38,764][grpc._server][ERROR] - Exception calling application: local variable 'dataset_info' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 49, in RegisterJob
    dataset_info=str(dataset_info),
UnboundLocalError: local variable 'dataset_info' referenced before assignment
[2025-03-05 18:37:46,617][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:37:46,622][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:37:46,636][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:37:51,305][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:37:51,306][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:38:17,819][SUPER][ERROR] - Failed to register job with dataset 's3://sdl-cifar10/test/'. Error: 'CentralBatchManager' object has no attribute 'jobs'
[2025-03-05 18:38:17,820][grpc._server][ERROR] - Exception calling application: local variable 'dataset_info' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 49, in RegisterJob
    dataset_info=str(dataset_info),
UnboundLocalError: local variable 'dataset_info' referenced before assignment
[2025-03-05 18:38:30,201][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:38:30,209][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:38:30,218][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:38:42,968][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:38:42,969][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:39:14,727][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:39:14,738][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:39:14,791][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:39:22,877][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:39:22,878][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:39:29,228][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 18:39:29,229][grpc._server][ERROR] - Exception calling application: local variable 'dataset_info' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 48, in RegisterJob
    dataset_info=str(dataset_info),
UnboundLocalError: local variable 'dataset_info' referenced before assignment
[2025-03-05 18:39:58,040][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:39:58,044][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:39:58,066][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:40:06,135][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:40:06,136][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:40:11,050][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 18:40:16,688][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 18:41:13,423][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:41:13,428][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:41:13,444][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:41:19,421][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:41:19,422][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:41:19,423][grpc._server][ERROR] - Exception calling application: local variable 'error_message' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 48, in RegisterJob
    errorMessage=error_message if error_message else None)
UnboundLocalError: local variable 'error_message' referenced before assignment
[2025-03-05 18:41:46,828][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:41:46,832][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:41:46,855][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:41:53,056][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:41:53,056][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:48:01,471][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:48:01,476][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:48:01,498][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:48:09,181][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:48:09,181][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:48:26,669][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 18:48:39,174][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 18:48:53,350][SUPER][INFO] - Job '4' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 4
[2025-03-05 18:49:35,287][SUPER][INFO] - Job '5' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 5
[2025-03-05 18:51:55,748][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:51:55,752][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:51:55,775][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:51:59,640][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:51:59,640][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:52:05,393][grpc._server][ERROR] - Exception calling application: data_dir
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 53, in GetNextBatchForJob
    data_dir = request.data_dir
AttributeError: data_dir
[2025-03-05 18:52:28,088][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:52:28,092][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:52:28,100][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:52:29,542][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:52:29,543][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:52:35,302][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 18:52:47,594][grpc._server][ERROR] - Exception calling application: Protocol message Batch has no "indicies" field.
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 61, in GetNextBatchForJob
    batch=minibatch_service_pb2.Batch(batch_id=next_batch.batch_id,
ValueError: Protocol message Batch has no "indicies" field.
[2025-03-05 18:53:09,492][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:53:09,497][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:53:09,511][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:53:14,505][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:53:14,505][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:53:21,813][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 18:53:40,527][grpc._server][ERROR] - Exception calling application: Protocol message Batch has no "indicies" field.
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 61, in GetNextBatchForJob
    batch=minibatch_service_pb2.Batch(
ValueError: Protocol message Batch has no "indicies" field.
[2025-03-05 18:54:17,713][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:54:17,717][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:54:17,730][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:54:23,104][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:54:23,105][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:54:23,109][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 18:54:25,686][grpc._server][ERROR] - Exception calling application: 'Batch' object has no attribute 'indicies'
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 63, in GetNextBatchForJob
    indices=next_batch.indicies,
AttributeError: 'Batch' object has no attribute 'indicies'
[2025-03-05 18:54:35,300][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:54:35,304][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:54:35,323][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:54:37,509][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:54:37,510][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:54:37,520][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 18:55:39,255][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 18:55:39,259][SUPER][INFO] - Job '2' assigned batch set '1_0'
[2025-03-05 18:57:46,689][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 18:57:46,693][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 18:57:46,704][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 18:57:49,629][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 18:57:49,629][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 18:57:49,636][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 18:57:49,640][grpc._server][ERROR] - Exception calling application: 'tuple' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 62, in GetNextBatchForJob
    batch=minibatch_service_pb2.Batch(
TypeError: 'tuple' object cannot be interpreted as an integer
[2025-03-05 18:57:58,367][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 18:57:58,369][SUPER][INFO] - Job '2' assigned batch set '1_0'
[2025-03-05 18:57:58,370][grpc._server][ERROR] - Exception calling application: 'tuple' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 62, in GetNextBatchForJob
    batch=minibatch_service_pb2.Batch(
TypeError: 'tuple' object cannot be interpreted as an integer
[2025-03-05 18:58:06,723][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 18:58:06,726][SUPER][INFO] - Job '3' assigned batch set '1_0'
[2025-03-05 18:58:27,762][grpc._server][ERROR] - Exception calling application: 'tuple' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 62, in GetNextBatchForJob
    batch=minibatch_service_pb2.Batch(
TypeError: 'tuple' object cannot be interpreted as an integer
[2025-03-05 19:02:41,135][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:02:41,139][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:02:41,148][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:02:45,385][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:02:45,386][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:02:45,395][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:03:36,532][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 19:03:36,534][SUPER][INFO] - Job '2' assigned batch set '1_0'
[2025-03-05 19:04:18,860][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 19:04:18,863][SUPER][INFO] - Job '3' assigned batch set '1_0'
[2025-03-05 19:05:12,543][SUPER][INFO] - Job '4' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 4
[2025-03-05 19:05:12,545][SUPER][INFO] - Job '4' assigned batch set '1_0'
[2025-03-05 19:05:57,755][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:05:57,759][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:05:57,771][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:06:08,329][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:06:08,330][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:06:08,335][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:12:17,589][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:12:17,595][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:12:17,627][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:12:19,798][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:12:19,798][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:12:19,803][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:13:38,266][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 19:13:38,268][SUPER][INFO] - Job '2' assigned batch set '1_0'
[2025-03-05 19:14:26,105][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 19:14:26,107][SUPER][INFO] - Job '3' assigned batch set '2_0'
[2025-03-05 19:14:55,261][SUPER][INFO] - Job '4' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 4
[2025-03-05 19:14:55,264][SUPER][INFO] - Job '4' assigned batch set '3_0'
[2025-03-05 19:15:45,887][SUPER][INFO] - Job '5' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 5
[2025-03-05 19:15:45,889][SUPER][INFO] - Job '5' assigned batch set '3_0'
[2025-03-05 19:16:03,139][SUPER][INFO] - Job '6' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 6
[2025-03-05 19:16:03,141][SUPER][INFO] - Job '6' assigned batch set '3_0'
[2025-03-05 19:16:21,423][SUPER][INFO] - Job '7' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 7
[2025-03-05 19:16:21,425][SUPER][INFO] - Job '7' assigned batch set '3_0'
[2025-03-05 19:16:37,958][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:16:37,962][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:16:37,986][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:16:45,598][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:16:45,599][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:16:45,605][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:17:27,116][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 19:17:27,118][SUPER][INFO] - Job '2' assigned batch set '2_0'
[2025-03-05 19:17:27,270][SUPER][INFO] - Job '2' assigned batch set '3_0'
[2025-03-05 19:17:37,516][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 19:17:37,518][SUPER][INFO] - Job '3' assigned batch set '4_0'
[2025-03-05 19:17:37,656][SUPER][INFO] - Job '3' assigned batch set '5_0'
[2025-03-05 19:22:08,218][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:22:08,222][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:22:08,233][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:22:25,117][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:22:25,118][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:22:25,122][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:22:25,257][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 19:22:38,360][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 19:22:38,362][SUPER][INFO] - Job '2' assigned batch set '3_0'
[2025-03-05 19:22:38,506][SUPER][INFO] - Job '2' assigned batch set '4_0'
[2025-03-05 19:22:42,369][grpc._server][ERROR] - Exception calling application: 'DLTJob' object has no attribute 'training_step_times_on_hit'
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 73, in JobEnded
    self.datasets[dataset_location].handle_job_ended(job_id=job_id)
  File "C:\Users\pw\projects\disdl\disdl\common\batch_manager.py", line 242, in handle_job_ended
    logger.info(f"Job '{job_id}' ended. Total time: {job.total_training_time():.4f}s, Steps: {job.total_training_steps()}, Hits: {job.training_step_times_on_hit.count}, Misses: {job.training_step_times_on_miss.count}, Rate: {job.training_step_times_on_hit.count / job.total_training_steps():.4f}" )
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 60, in total_training_time
    return self.training_step_times_on_hit.sum + self.training_step_times_on_miss.sum
AttributeError: 'DLTJob' object has no attribute 'training_step_times_on_hit'
[2025-03-05 19:22:52,058][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 19:22:52,062][SUPER][INFO] - Job '3' assigned batch set '5_0'
[2025-03-05 19:22:52,201][SUPER][INFO] - Job '3' assigned batch set '6_0'
[2025-03-05 19:24:03,109][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:24:03,113][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:24:03,128][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:24:07,751][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:24:07,752][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:24:07,756][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:24:07,888][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 19:24:15,256][grpc._server][ERROR] - Exception calling application: 'DLTJob' object has no attribute 'training_step_times_on_hit'
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 73, in JobEnded
    self.datasets[dataset_location].handle_job_ended(job_id=job_id)
  File "C:\Users\pw\projects\disdl\disdl\common\batch_manager.py", line 242, in handle_job_ended
    logger.info(f"Job '{job_id}' ended.  Lifetime: {job.total_training_time():.4f}s" )
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 60, in total_training_time
    return self.training_step_times_on_hit.sum + self.training_step_times_on_miss.sum
AttributeError: 'DLTJob' object has no attribute 'training_step_times_on_hit'
[2025-03-05 19:25:15,036][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:25:15,040][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:25:15,050][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:25:19,014][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:25:19,015][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:25:19,020][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:25:19,180][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 19:25:26,041][grpc._server][ERROR] - Exception calling application: 'DLTJob' object has no attribute 'training_step_times_on_hit'
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 73, in JobEnded
    self.datasets[dataset_location].handle_job_ended(job_id=job_id)
  File "C:\Users\pw\projects\disdl\disdl\common\batch_manager.py", line 243, in handle_job_ended
    logger.info(f"Job '{job_id}' ended. Lifetime: {job.total_training_time():.4f}s. Active Jobs {len(self.active_jobs)}" )
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 60, in total_training_time
    return self.training_step_times_on_hit.sum + self.training_step_times_on_miss.sum
AttributeError: 'DLTJob' object has no attribute 'training_step_times_on_hit'
[2025-03-05 19:25:45,797][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:25:45,803][SUPER][INFO] - Job '2' assigned batch set '3_0'
[2025-03-05 19:25:46,029][SUPER][INFO] - Job '2' assigned batch set '4_0'
[2025-03-05 19:25:46,215][grpc._server][ERROR] - Exception calling application: 'DLTJob' object has no attribute 'training_step_times_on_hit'
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 73, in JobEnded
    self.datasets[dataset_location].handle_job_ended(job_id=job_id)
  File "C:\Users\pw\projects\disdl\disdl\common\batch_manager.py", line 243, in handle_job_ended
    logger.info(f"Job '{job_id}' ended. Lifetime: {job.total_training_time():.4f}s. Active Jobs {len(self.active_jobs)}" )
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 60, in total_training_time
    return self.training_step_times_on_hit.sum + self.training_step_times_on_miss.sum
AttributeError: 'DLTJob' object has no attribute 'training_step_times_on_hit'
[2025-03-05 19:27:14,896][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:27:14,900][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:27:14,918][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:27:19,465][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:27:19,466][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:27:19,472][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:27:19,604][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 19:27:19,737][SUPER][INFO] - Job '1' ended. Lifetime: 0.2705s. Active Jobs 0
[2025-03-05 19:27:31,161][grpc._server][ERROR] - Exception calling application: 'PrefetchService' object has no attribute 'prefetch_lambda_invocations_count'
Traceback (most recent call last):
  File "c:\Users\pw\miniconda3\envs\disdl\lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\pw\projects\disdl\disdl\server.py", line 73, in JobEnded
    self.datasets[dataset_location].handle_job_ended(job_id=job_id)
  File "C:\Users\pw\projects\disdl\disdl\common\batch_manager.py", line 249, in handle_job_ended
    self.prefetch_service.stop_prefetcher()
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 224, in stop_prefetcher
    logger.info(f"Prefetcher stopped. Total requests: {self.prefetch_lambda_invocations_count}, Total execution time: {self.prefetch_lambda_execution_times.sum:.2f}s, Total cost: ${self._compute_prefeteching_cost():.4f}")
AttributeError: 'PrefetchService' object has no attribute 'prefetch_lambda_invocations_count'
[2025-03-05 19:28:11,975][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:28:11,979][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:28:11,994][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:28:16,523][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:28:16,525][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:28:16,531][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:28:16,663][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 19:28:16,791][SUPER][INFO] - Job '1' ended. Lifetime: 0.2669s. Active Jobs 0
[2025-03-05 19:28:19,622][SUPER][INFO] - Prefetching stopped
[2025-03-05 19:28:21,182][SUPER][INFO] - Cache eviction service stopped
[2025-03-05 19:38:44,707][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:38:44,721][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,727][SUPER][INFO] - Job '2' assigned batch set '3_0'
[2025-03-05 19:38:44,731][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,736][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,736][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,737][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,738][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,739][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,741][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,741][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,743][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,743][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,746][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,747][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,749][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,749][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,751][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,751][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,753][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,754][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,755][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,757][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,757][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,759][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,760][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,762][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,762][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,764][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,765][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,768][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,768][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,770][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,771][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,772][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,774][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,775][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,776][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,777][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,777][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,779][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,780][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,780][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,783][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,783][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,784][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,785][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,787][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,788][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,789][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,790][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,791][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,791][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,793][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,793][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,795][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,796][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,797][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,799][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,799][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,801][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,801][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,803][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,803][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,805][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,805][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,807][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,807][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,809][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,810][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,811][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,812][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,813][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,815][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,816][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,818][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,819][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,820][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,821][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,822][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,824][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,825][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,826][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,827][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,828][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,831][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,833][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,834][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,836][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,837][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,838][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,840][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,841][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,842][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,843][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,845][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,847][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,849][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,850][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,850][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,852][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,853][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,854][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,855][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,856][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,857][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,858][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,859][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,860][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,860][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,861][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,876][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,877][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,878][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,880][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,882][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,883][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,885][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,885][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,888][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,888][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,890][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,890][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,892][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,893][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,895][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,897][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,898][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,899][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,901][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,902][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,903][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,905][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,905][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,907][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,908][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,911][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,912][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,913][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,916][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,918][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,919][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,920][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,921][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,922][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,924][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,925][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,927][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,927][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,928][SUPER][INFO] - Job '2' assigned batch set '4_0'
[2025-03-05 19:38:44,928][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,931][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,932][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,933][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,934][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,935][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,936][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,938][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,940][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,940][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,942][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,943][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,944][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,947][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,949][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,951][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,951][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,953][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,955][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,958][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,959][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,960][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,961][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,962][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,964][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,966][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,967][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,968][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,969][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,970][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,971][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,973][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,973][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,974][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,976][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,976][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,978][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,980][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,981][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,982][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,983][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,984][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,985][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,987][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,987][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,989][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,989][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,991][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,991][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,993][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,995][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,995][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,997][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:44,998][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,000][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,001][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,002][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,003][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,004][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,004][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,005][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,006][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,008][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,009][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,010][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,011][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,011][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,013][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,015][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,016][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,017][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,018][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,020][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,020][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,022][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,023][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,024][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,025][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,026][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,027][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,027][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,030][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,031][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,032][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,033][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,034][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,035][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,036][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,038][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,039][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,040][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,042][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,042][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,044][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,046][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,048][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,050][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,050][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,052][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,053][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,055][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,057][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,057][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,071][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,072][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,073][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,074][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,074][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,076][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,076][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,078][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,080][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,081][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,083][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,083][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,085][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,085][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,088][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,088][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,090][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,090][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,092][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,092][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,094][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,095][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,096][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,097][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,099][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,100][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,102][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,103][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,104][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,106][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,107][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,109][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,110][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,111][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,112][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,114][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,115][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,117][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,118][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,120][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,121][SUPER][ERROR] - Unexpected error in prefetching process: division by zero
Traceback (most recent call last):
  File "C:\Users\pw\projects\disdl\disdl\common\cache_prefetching.py", line 57, in _prefetching_process
  File "C:\Users\pw\projects\disdl\disdl\common\job.py", line 30, in compute_required_prefetch_concurrency
ZeroDivisionError: division by zero
[2025-03-05 19:38:45,121][SUPER][INFO] - Job '2' ended. Lifetime: 0.4187s. Active Jobs 0
[2025-03-05 19:44:03,080][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 19:44:03,086][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 19:44:03,107][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 19:44:17,887][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 19:44:17,888][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 19:44:17,895][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 19:44:18,079][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 19:44:18,276][SUPER][INFO] - Job '1' ended. Lifetime: 0.3881s. Active Jobs 0
[2025-03-05 19:44:18,277][SUPER][INFO] - Prefetching stopped
[2025-03-05 19:44:18,277][SUPER][INFO] - Cache eviction service stopped
[2025-03-05 20:54:14,732][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 20:54:14,736][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 20:54:14,773][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 20:54:56,865][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 20:54:56,865][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 20:55:52,401][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 20:55:59,585][SUPER][INFO] - Job '2' assigned batch set '1_0'
[2025-03-05 20:56:32,836][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 20:56:34,280][SUPER][INFO] - Job '3' assigned batch set '1_0'
[2025-03-05 20:56:34,405][SUPER][INFO] - Job '3' assigned batch set '2_0'
[2025-03-05 20:56:34,530][SUPER][INFO] - Job '3' assigned batch set '3_0'
[2025-03-05 20:56:34,652][SUPER][INFO] - Job '3' assigned batch set '4_0'
[2025-03-05 20:56:34,796][SUPER][INFO] - Job '3' assigned batch set '5_0'
[2025-03-05 20:56:34,919][SUPER][INFO] - Job '3' assigned batch set '6_0'
[2025-03-05 20:56:35,042][SUPER][INFO] - Job '3' assigned batch set '7_0'
[2025-03-05 20:56:35,187][SUPER][INFO] - Job '3' assigned batch set '8_0'
[2025-03-05 20:56:35,309][SUPER][INFO] - Job '3' assigned batch set '9_0'
[2025-03-05 20:56:35,429][SUPER][INFO] - Job '3' assigned batch set '10_0'
[2025-03-05 20:56:35,554][SUPER][INFO] - Job '3' assigned batch set '11_0'
[2025-03-05 20:56:35,677][SUPER][INFO] - Job '3' assigned batch set '12_0'
[2025-03-05 20:56:35,815][SUPER][INFO] - Job '3' assigned batch set '13_0'
[2025-03-05 20:56:35,941][SUPER][INFO] - Job '3' assigned batch set '14_0'
[2025-03-05 20:56:36,068][SUPER][INFO] - Job '3' assigned batch set '15_0'
[2025-03-05 20:56:36,266][SUPER][INFO] - Job '3' assigned batch set '16_0'
[2025-03-05 20:56:36,414][SUPER][INFO] - Job '3' assigned batch set '17_0'
[2025-03-05 20:56:36,537][SUPER][INFO] - Job '3' assigned batch set '18_0'
[2025-03-05 20:56:36,662][SUPER][INFO] - Job '3' assigned batch set '19_0'
[2025-03-05 20:56:36,818][SUPER][INFO] - Job '3' assigned batch set '20_0'
[2025-03-05 20:56:36,980][SUPER][INFO] - Job '3' assigned batch set '21_0'
[2025-03-05 20:56:37,109][SUPER][INFO] - Job '3' assigned batch set '22_0'
[2025-03-05 20:56:37,232][SUPER][INFO] - Job '3' assigned batch set '23_0'
[2025-03-05 20:56:37,372][SUPER][INFO] - Job '3' assigned batch set '24_0'
[2025-03-05 20:56:37,498][SUPER][INFO] - Job '3' assigned batch set '25_0'
[2025-03-05 20:56:37,622][SUPER][INFO] - Job '3' assigned batch set '26_0'
[2025-03-05 20:56:37,747][SUPER][INFO] - Job '3' assigned batch set '27_0'
[2025-03-05 20:56:37,870][SUPER][INFO] - Job '3' assigned batch set '28_0'
[2025-03-05 20:56:37,993][SUPER][INFO] - Job '3' assigned batch set '29_0'
[2025-03-05 20:56:38,116][SUPER][INFO] - Job '3' assigned batch set '30_0'
[2025-03-05 20:56:38,239][SUPER][INFO] - Job '3' assigned batch set '31_0'
[2025-03-05 20:56:38,403][SUPER][INFO] - Job '3' assigned batch set '32_0'
[2025-03-05 20:56:38,615][SUPER][INFO] - Job '3' assigned batch set '33_0'
[2025-03-05 20:56:38,753][SUPER][INFO] - Job '3' assigned batch set '34_0'
[2025-03-05 20:56:38,878][SUPER][INFO] - Job '3' assigned batch set '35_0'
[2025-03-05 20:56:39,009][SUPER][INFO] - Job '3' assigned batch set '36_0'
[2025-03-05 20:56:39,154][SUPER][INFO] - Job '3' assigned batch set '37_0'
[2025-03-05 20:56:56,903][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 20:56:56,907][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 20:56:56,923][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 20:57:02,545][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 20:57:02,546][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 20:57:09,089][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 20:57:11,539][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 20:58:34,434][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 20:58:34,443][SUPER][INFO] - Job '2' assigned batch set '2_0'
[2025-03-05 20:58:37,908][SUPER][INFO] - Job '2' assigned batch set '3_0'
[2025-03-05 20:59:00,033][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 20:59:00,042][SUPER][INFO] - Job '3' assigned batch set '3_0'
[2025-03-05 21:00:53,646][SUPER][INFO] - Job '4' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 4
[2025-03-05 21:01:03,459][SUPER][INFO] - Job '4' assigned batch set '3_0'
[2025-03-05 21:02:14,935][SUPER][INFO] - Job '5' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 5
[2025-03-05 21:02:15,565][SUPER][INFO] - Job '5' assigned batch set '3_0'
[2025-03-05 21:02:33,371][SUPER][INFO] - Job '6' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 6
[2025-03-05 21:02:33,380][SUPER][INFO] - Job '6' assigned batch set '3_0'
[2025-03-05 21:04:38,690][SUPER][INFO] - Job '7' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 7
[2025-03-05 21:04:38,700][SUPER][INFO] - Job '7' assigned batch set '3_0'
[2025-03-05 21:05:36,827][SUPER][INFO] - Job '8' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 8
[2025-03-05 21:05:36,837][SUPER][INFO] - Job '8' assigned batch set '4_0'
[2025-03-05 21:06:07,186][SUPER][INFO] - Job '9' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 9
[2025-03-05 21:06:07,195][SUPER][INFO] - Job '9' assigned batch set '4_0'
[2025-03-05 21:06:42,987][SUPER][INFO] - Job '10' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 10
[2025-03-05 21:06:42,996][SUPER][INFO] - Job '10' assigned batch set '4_0'
[2025-03-05 21:07:38,992][SUPER][INFO] - Job '11' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 11
[2025-03-05 21:07:40,283][SUPER][INFO] - Job '11' assigned batch set '4_0'
[2025-03-05 21:08:04,468][SUPER][INFO] - Job '12' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 12
[2025-03-05 21:08:05,697][SUPER][INFO] - Job '12' assigned batch set '4_0'
[2025-03-05 21:08:33,461][SUPER][INFO] - Job '13' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 13
[2025-03-05 21:08:34,699][SUPER][INFO] - Job '13' assigned batch set '4_0'
[2025-03-05 21:11:04,798][SUPER][INFO] - Job '14' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 14
[2025-03-05 21:11:06,056][SUPER][INFO] - Job '14' assigned batch set '4_0'
[2025-03-05 21:12:59,039][SUPER][INFO] - Job '15' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 15
[2025-03-05 21:13:48,323][SUPER][INFO] - Job '16' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 16
[2025-03-05 21:15:52,513][SUPER][INFO] - Job '17' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 17
[2025-03-05 21:16:50,104][SUPER][INFO] - Job '18' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 18
[2025-03-05 21:16:56,572][SUPER][INFO] - Job '18' assigned batch set '4_0'
[2025-03-05 21:17:43,870][SUPER][INFO] - Job '18' assigned batch set '5_0'
[2025-03-05 21:18:17,055][SUPER][INFO] - Starting DisDL ML Dataloader Service
[2025-03-05 21:18:17,059][SUPER][INFO] - Config: lookahead_steps: 100
serverless_cache_address: 10.0.21.36:6378
cache_evition_ttl_threshold: 1000
use_prefetching: true
use_keep_alive: true
prefetch_cost_cap_per_hour: null
prefetch_simulation_time: null
evict_from_cache_simulation_time: null
workload:
  kind: vision
  batch_size: 128
  shuffle: true
  drop_last: false
  prefetch_lambda_name: CreateVisionTrainingBatch
  max_dataset_size: null
  num_dataset_partitions: 1

[2025-03-05 21:18:17,076][SUPER][INFO] - Server started. Listening on port 50051 with 1 workers.
[2025-03-05 21:18:28,881][SUPER][INFO] - Dataset 's3://sdl-cifar10/test/' added. Total Files: 10000, Total Batches:79
[2025-03-05 21:18:28,882][SUPER][INFO] - Job '1' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 1
[2025-03-05 21:18:35,836][SUPER][INFO] - Job '1' assigned batch set '1_0'
[2025-03-05 21:19:42,245][SUPER][INFO] - Job '1' assigned batch set '2_0'
[2025-03-05 21:20:37,691][SUPER][INFO] - Job '2' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 2
[2025-03-05 21:20:43,572][SUPER][INFO] - Job '2' assigned batch set '2_0'
[2025-03-05 21:22:16,819][SUPER][INFO] - Job '3' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 3
[2025-03-05 21:22:24,099][SUPER][INFO] - Job '3' assigned batch set '3_0'
[2025-03-05 21:23:17,741][SUPER][INFO] - Job '4' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 4
[2025-03-05 21:23:50,638][SUPER][INFO] - Job '4' assigned batch set '3_0'
[2025-03-05 21:24:38,840][SUPER][INFO] - Job '5' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 5
[2025-03-05 21:24:46,474][SUPER][INFO] - Job '5' assigned batch set '3_0'
[2025-03-05 21:26:35,067][SUPER][INFO] - Job '6' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 6
[2025-03-05 21:26:51,687][SUPER][INFO] - Job '6' assigned batch set '4_0'
[2025-03-05 21:27:49,936][SUPER][INFO] - Job '7' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 7
[2025-03-05 21:28:01,261][SUPER][INFO] - Job '7' assigned batch set '4_0'
[2025-03-05 21:28:49,149][SUPER][INFO] - Job '8' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 8
[2025-03-05 21:28:50,389][SUPER][INFO] - Job '8' assigned batch set '4_0'
[2025-03-05 21:29:26,106][SUPER][INFO] - Job '9' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 9
[2025-03-05 21:29:33,319][SUPER][INFO] - Job '9' assigned batch set '4_0'
[2025-03-05 21:30:08,660][SUPER][INFO] - Job '10' registered for dataset 's3://sdl-cifar10/test/'. Total Jobs: 10
[2025-03-05 21:30:15,372][SUPER][INFO] - Job '10' assigned batch set '5_0'
